# Combines all .cs files in the Tebex.Headless namespace into a single file.
# Excludes .cs.old backup files. Deduplicates `using` directives and wraps
# all type declarations in a single `namespace Tebex.Headless { ... }` block.

[CmdletBinding()]
param(
    [string]$SourceDir = (Join-Path $PSScriptRoot ''),
    [string]$OutputFile = (Join-Path $PSScriptRoot 'Tebex.Headless.Combined.cs'),
    [string]$Namespace  = 'Tebex.Headless'
)

$ErrorActionPreference = 'Stop'

$files = Get-ChildItem -Path $SourceDir -Filter *.cs -File |
    Where-Object { $_.Name -ne (Split-Path $OutputFile -Leaf) } |
    Sort-Object Name

if (-not $files) {
    Write-Error "No .cs files found in '$SourceDir'."
    return
}

$usings = [System.Collections.Generic.SortedSet[string]]::new()
$bodies = [System.Collections.Generic.List[string]]::new()

# Patterns: capture `using X;` (not `using static` aliases differently — keep them too)
$usingPattern     = '^\s*using\s+[^;]+;\s*$'
$namespaceOpenRe  = '^\s*namespace\s+[\w\.]+\s*\{?\s*$'

foreach ($file in $files) {
    $lines = Get-Content -LiteralPath $file.FullName

    $bodyLines = [System.Collections.Generic.List[string]]::new()
    $inNamespace = $false
    $braceDepth  = 0
    $sawNamespaceBrace = $false

    foreach ($line in $lines) {
        if (-not $inNamespace) {
            if ($line -match $usingPattern) {
                [void]$usings.Add($line.Trim())
                continue
            }
            if ($line -match $namespaceOpenRe) {
                $inNamespace = $true
                # If `{` is on the same line, account for it; else expect it next.
                if ($line -match '\{') { $sawNamespaceBrace = $true; $braceDepth = 1 }
                continue
            }
            # Skip blank lines / file-level comments before namespace
            if ([string]::IsNullOrWhiteSpace($line)) { continue }
            # Anything else outside the namespace (e.g. file-scoped attributes) — keep it.
            $bodyLines.Add($line)
            continue
        }

        # Inside namespace: track braces so we can drop the closing one.
        if (-not $sawNamespaceBrace) {
            if ($line -match '^\s*\{\s*$') {
                $sawNamespaceBrace = $true
                $braceDepth = 1
                continue
            }
        }

        $opens  = ([regex]::Matches($line, '\{')).Count
        $closes = ([regex]::Matches($line, '\}')).Count
        $newDepth = $braceDepth + $opens - $closes

        if ($newDepth -le 0) {
            # This line contains the namespace's closing brace; drop it.
            $braceDepth = 0
            $inNamespace = $false
            continue
        }

        $bodyLines.Add($line)
        $braceDepth = $newDepth
    }

    # Indent body by 4 spaces so it sits cleanly inside the wrapping namespace.
    $indented = $bodyLines | ForEach-Object {
        if ([string]::IsNullOrWhiteSpace($_)) { '' } else { '    ' + $_ }
    }

    $bodies.Add("    // ===== $($file.Name) =====")
    $bodies.AddRange([string[]]$indented)
    $bodies.Add('')
}

$output = [System.Collections.Generic.List[string]]::new()
$output.Add("// <auto-generated>")
$output.Add("// Combined from $($files.Count) files in namespace $Namespace.")
$output.Add("// Generated $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').")
$output.Add("// </auto-generated>")
$output.Add('')
foreach ($u in $usings) { $output.Add($u) }
$output.Add('')
$output.Add("namespace $Namespace")
$output.Add('{')
$output.AddRange([string[]]$bodies)
$output.Add('}')

Set-Content -LiteralPath $OutputFile -Value $output -Encoding UTF8
Write-Host "Combined $($files.Count) files -> $OutputFile"
Write-Host "Unique using directives: $($usings.Count)"
